import { Prize, Show } from "./types";

export const radioStations = [
  {
    name: "Brabo FM",
    streamUrl: "https://stm16.xcast.com.br:9186/stream", 
    currentSong: "Sem informação",
    currentSongImage: ""
  }
];

export const showsData: Show[] = [
  {
    // Segunda-feira (day: 1)
    id: 1,
    title: "Classicos da Braba",
    host: "Paulinho do Povo",
    time: "07:00 - 09:15",
    day: 1,
    description: "Os clássicos que marcaram época, você ouve aqui!",
    image: "/images/Programas/classicosBraba.png"
  },
  {
    id: 2,
    title: "Manhã Sertaneja",
    host: "Paulinho do Povo",
    time: "07:00 - 09:15",
    day: 1,
    description: "Comece o dia com muita energia e as melhores músicas sertanejas!",
    image: "/images/Programas/manhaSertaneja.png"
  },
  {
    id: 3,
    title: "Bom Dia Homem do Campo",
    host: "Toninho",
    time: "09:30 - 11:00",
    day: 1,
    description: "Notícias, dicas e muita música para o homem do campo.",
    image: "/images/Programas/homemCampo.png"
  },
  {
    id: 4,
    title: "Bate-Bola com Nenê Quevedo",
    host: "",
    time: "11:00 - 13:00",
    day: 1,
    description: "Tudo sobre futebol com os comentarios de Nenê Quevedo.",
    image: "/images/Programas/bateBola.png"
  },
  {
    id: 5,
    title: "As Brabas do Momento 1ª Edição",
    host: "Fred",
    time: "13:00 - 14:30",
    day: 1,
    description: "As músicas mais tocadas do momento, você ouve aqui!",
    image: "/images/Programas/brabasMomento1.png"
  },
  {
    id: 6,
    title: "Solta a Braba!",
    host: "",
    time: "14:30 - 17:00",
    day: 1,
    description: "As músicas mais tocadas do momento, você ouve aqui!",
    image: "/images/Programas/soltaaBraba.png"
  },
  {
    id: 7,
    title: "Hora do Rush",
    host: "",
    time: "17:00 - 18:00",
    day: 1,
    description: "Hora do Rush na Braba pra chegar em casa bem informado e bem acompanhado!",
    image: "/images/Programas/horadoRush.png"
  },
  {
    id: 8,
    title: "Tarde de Bençãos",
    host: "",
    time: "18:00 - 19:00",
    day: 1,
    description: "Músicas evangélicas para abençoar sua tarde.",
    image: "/images/Programas/tardeBencaos.png"
  },
  {
    id: 9,
    title: "Na Xinxa Xou!",
    host: "Felipe Branco",
    time: "20:00 - 21:30",
    day: 1,
    description: "O humor e a irreverência de Felipe Branco para animar sua noite.",
    image: "/images/Programas/naXinxaXou.png"
  },
  {
    id: 10,
    title: "As Brabas do Momento 2ª Edição",
    host: "",
    time: "21:30 - 00:00",
    day: 1,
    description: "As músicas mais tocadas do momento, você ouve aqui!",
    image: "/images/Programas/brabasMomento2.png"
  },
  {
    id: 11,
    title: "Madrugada Braba",
    host: "",
    time: "00:00 - 04:00",
    day: 1,
    description: "Músicas para quem está acordado de madrugada.",
    image: "/images/Programas/madrugadaBraba.png"
  },
    // Terça-Feira (day: 2)
  {
    id: 12,
    title: "Classicos da Braba",
    host: "Paulinho do Povo",
    time: "07:00 - 09:15",
    day: 2, 
    description: "Os clássicos que marcaram época, você ouve aqui!",
    image: "/images/Programas/classicosBraba.png"
  },
  {
    id: 13,
    title: "Manhã Sertaneja",
    host: "Paulinho do Povo",
    time: "07:00 - 09:15",
    day: 2, 
    description: "Comece o dia com muita energia e as melhores músicas sertanejas!",
    image: "/images/Programas/manhaSertaneja.png"
  },
  {
    id: 14,
    title: "Bom Dia Homem do Campo",
    host: "Toninho",
    time: "09:30 - 11:00",
    day: 2, 
    description: "Notícias, dicas e muita música para o homem do campo.",
    image: "/images/Programas/homemCampo.png"
  },
  {
    id: 15,
    title: "Na Braba Informa com Gersinho Rádio e TV",
    host: "Gersinho",
    time: "11:00 - 13:00",
    day: 2, 
    description: "As principais notícias do dia com a credibilidade de Gersinho Rádio e TV.",
    image: "/images/Programas/brabaInforma.png"
  },
  {
    id: 16,
    title: "As Brabas do Momento 1ª Edição",
    host: "Fred",
    time: "13:00 - 14:30",
    day: 2, 
    description: "As músicas mais tocadas do momento, você ouve aqui!",
    image: "/images/Programas/brabasMomento1.png"
  },
  {
    id: 17,
    title: "Solta a Braba!",
    host: "",
    time: "14:30 - 17:00",
    day: 2, 
    description: "As músicas mais tocadas do momento, você ouve aqui!",
    image: "/images/Programas/soltaaBraba.png"
  },
  {
    id: 18,
    title: "Hora do Rush",
    host: "",
    time: "17:00 - 18:00",
    day: 2, 
    description: "Hora do Rush na Braba pra chegar em casa bem informado e bem acompanhado!",
    image: "/images/Programas/horadoRush.png"
  },
  {
    id: 19,
    title: "Tarde de Bençãos",
    host: "",
    time: "18:00 - 19:00",
    day: 2, 
    description: "Músicas evangélicas para abençoar sua tarde.",
    image: "/images/Programas/tardeBencaos.png"
  },
  {
    id: 20,
    title: "Na Xinxa Xou!",
    host: "Felipe Branco",
    time: "20:00 - 21:30",
    day: 2, 
    description: "O humor e a irreverência de Felipe Branco para animar sua noite.",
    image: "/images/Programas/naXinxaXou.png"
  },
  {
    id: 21,
    title: "As Brabas do Momento 2ª Edição",
    host: "",
    time: "21:30 - 00:00",
    day: 2, 
    description: "As músicas mais tocadas do momento, você ouve aqui!",
    image: "/images/Programas/brabasMomento2.png"
  },
  {
    id: 22,
    title: "Madrugada Braba",
    host: "",
    time: "21:30 - 00:00",
    day: 2, 
    description: "Músicas para quem está acordado de madrugada.",
    image: "/images/Programas/madrugadaBraba.png"
  },
  // Quarta-feira (day: 3)
  {
    id: 23,
    title: "Classicos da Braba",
    host: "Paulinho do Povo",
    time: "07:00 - 09:15",
    day: 3,
    description: "Os clássicos que marcaram época, você ouve aqui!",
    image: "/images/Programas/classicosBraba.png",
  },
  {
    id: 24,
    title: "Manhã Sertaneja",
    host: "Paulinho do Povo",
    time: "07:00 - 09:15",
    day: 3,
    description: "Comece o dia com muita energia e as melhores músicas sertanejas!",
    image: "/images/Programas/manhaSertaneja.png",
  },
  {
    id: 25,
    title: "Bom Dia Homem do Campo",
    host: "Toninho",
    time: "09:30 - 11:00",
    day: 3,
    description: "Notícias, dicas e muita música para o homem do campo.",
    image: "/images/Programas/homemCampo.png",
  },
  {
    id: 26,
    title: "Na Braba Informa com Gersinho Rádio e TV",
    host: "Gersinho",
    time: "11:00 - 13:00",
    day: 3,
    description: "As principais notícias do dia com a credibilidade de Gersinho Rádio e TV.",
    image: "/images/Programas/brabaInforma.png",
  },
  {
    id: 27,
    title: "As Brabas do Momento 1ª Edição",
    host: "Fred",
    time: "13:00 - 14:30",
    day: 3,
    description: "As músicas mais tocadas do momento, você ouve aqui!",
    image: "/images/Programas/brabasMomento1.png",
  },
  {
    id: 28,
    title: "Solta a Braba!",
    host: "",
    time: "14:30 - 17:00",
    day: 3,
    description: "As músicas mais tocadas do momento, você ouve aqui!",
    image: "/images/Programas/soltaaBraba.png",
  },
  {
    id: 29,
    title: "Hora do Rush",
    host: "",
    time: "17:00 - 18:00",
    day: 3,
    description: "Hora do Rush na Braba pra chegar em casa bem informado e bem acompanhado!",
    image: "/images/Programas/horadoRush.png",
  },
  {
    id: 30,
    title: "Tarde de Bençãos",
    host: "",
    time: "18:00 - 19:00",
    day: 3,
    description: "Músicas evangélicas para abençoar sua tarde.",
    image: "/images/Programas/tardeBencaos.png",
  },
  {
    id: 31,
    title: "Na Xinxa Xou!",
    host: "Felipe Branco",
    time: "20:00 - 21:30",
    day: 3,
    description: "O humor e a irreverência de Felipe Branco para animar sua noite.",
    image: "/images/Programas/naXinxaXou.png",
  },
  {
    id: 32,
    title: "As Brabas do Momento 2ª Edição",
    host: "",
    time: "21:30 - 00:00",
    day: 3,
    description: "As músicas mais tocadas do momento, você ouve aqui!",
    image: "/images/Programas/brabasMomento2.png",
  },
  {
    id: 33,
    title: "Madrugada Braba",
    host: "",
    time: "21:30 - 00:00",
    day: 3,
    description: "Músicas para quem está acordado de madrugada.",
    image: "/images/Programas/madrugadaBraba.png",
  },
  // Quinta-feira (day: 4)
  {
    id: 34,
    title: "Classicos da Braba",
    host: "Paulinho do Povo",
    time: "07:00 - 09:15",
    day: 4,
    description: "Os clássicos que marcaram época, você ouve aqui!",
    image: "/images/Programas/classicosBraba.png",
  },
  {
    id: 35,
    title: "Manhã Sertaneja",
    host: "Paulinho do Povo",
    time: "07:00 - 09:15",
    day: 4,
    description: "Comece o dia com muita energia e as melhores músicas sertanejas!",
    image: "/images/Programas/manhaSertaneja.png",
  },
  {
    id: 36,
    title: "Bom Dia Homem do Campo",
    host: "Toninho",
    time: "09:30 - 11:00",
    day: 4,
    description: "Notícias, dicas e muita música para o homem do campo.",
    image: "/images/Programas/homemCampo.png",
  },
  {
    id: 37,
    title: "Bate-Bola com Nenê Quevedo",
    host: "",
    time: "11:00 - 13:00",
    day: 4,
    description: "Tudo sobre futebol com os comentarios de Nenê Quevedo.",
    image: "/images/Programas/bateBola.png",
  },
  {
    id: 38,
    title: "As Brabas do Momento 1ª Edição",
    host: "Fred",
    time: "13:00 - 14:30",
    day: 4,
    description: "As músicas mais tocadas do momento, você ouve aqui!",
    image: "/images/Programas/brabasMomento1.png",
  },
  {
    id: 39,
    title: "Solta a Braba!",
    host: "",
    time: "14:30 - 17:00",
    day: 4,
    description: "As músicas mais tocadas do momento, você ouve aqui!",
    image: "/images/Programas/soltaaBraba.png",
  },
  {
    id: 40,
    title: "Hora do Rush",
    host: "",
    time: "17:00 - 18:00",
    day: 4,
    description: "Hora do Rush na Braba pra chegar em casa bem informado e bem acompanhado!",
    image: "/images/Programas/horadoRush.png",
  },
  {
    id: 41,
    title: "Tarde de Bençãos",
    host: "",
    time: "18:00 - 19:00",
    day: 4,
    description: "Músicas evangélicas para abençoar sua tarde.",
    image: "/images/Programas/tardeBencaos.png",
  },
  {
    id: 42,
    title: "Na Xinxa Xou!",
    host: "Felipe Branco",
    time: "20:00 - 21:30",
    day: 4,
    description: "O humor e a irreverência de Felipe Branco para animar sua noite.",
    image: "/images/Programas/naXinxaXou.png",
  },
  {
    id: 43,
    title: "As Brabas do Momento 2ª Edição",
    host: "",
    time: "21:30 - 00:00",
    day: 4,
    description: "As músicas mais tocadas do momento, você ouve aqui!",
    image: "/images/Programas/brabasMomento2.png",
  },
  {
    id: 44,
    title: "Madrugada Braba",
    host: "",
    time: "00:00 - 04:00",
    day: 4,
    description: "Músicas para quem está acordado de madrugada.",
    image: "/images/Programas/madrugadaBraba.png",
  },
  // Sexta-feira (day: 5)
  {
    id: 45,
    title: "Classicos da Braba",
    host: "Paulinho do Povo",
    time: "07:00 - 09:15",
    day: 5,
    description: "Os clássicos que marcaram época, você ouve aqui!",
    image: "/images/Programas/classicosBraba.png",
  },
  {
    id: 46,
    title: "Manhã Sertaneja",
    host: "Paulinho do Povo",
    time: "07:00 - 09:15",
    day: 5,
    description: "Comece o dia com muita energia e as melhores músicas sertanejas!",
    image: "/images/Programas/manhaSertaneja.png",
  },
  {
    id: 47,
    title: "Na Braba Informa com Gersinho Rádio e TV",
    host: "Gersinho",
    time: "11:00 - 13:00",
    day: 5,
    description: "As principais notícias do dia com a credibilidade de Gersinho Rádio e TV.",
    image: "/images/Programas/brabaInforma.png",
  },
  {
    id: 48,
    title: "As Brabas do Momento 1ª Edição",
    host: "Fred",
    time: "13:00 - 14:30",
    day: 5,
    description: "As músicas mais tocadas do momento, você ouve aqui!",
    image: "/images/Programas/brabasMomento1.png",
  },
  {
    id: 49,
    title: "Solta a Braba!",
    host: "",
    time: "14:30 - 17:00",
    day: 5,
    description: "As músicas mais tocadas do momento, você ouve aqui!",
    image: "/images/Programas/soltaaBraba.png",
  },
  {
    id: 50,
    title: "Hora do Rush",
    host: "",
    time: "17:00 - 18:00",
    day: 5,
    description: "Hora do Rush na Braba pra chegar em casa bem informado e bem acompanhado!",
    image: "/images/Programas/horadoRush.png",
  },
  {
    id: 51,
    title: "Tarde de Bençãos",
    host: "",
    time: "18:00 - 19:00",
    day: 5,
    description: "Músicas evangélicas para abençoar sua tarde.",
    image: "/images/Programas/tardeBencaos.png",
  },
  {
    id: 52,
    title: "As Brabas do Momento 2ª Edição",
    host: "",
    time: "21:30 - 00:00",
    day: 5,
    description: "As músicas mais tocadas do momento, você ouve aqui!",
    image: "/images/Programas/brabasMomento2.png",
  },
  {
    id: 53,
    title: "Madrugada Braba",
    host: "",
    time: "00:00 - 04:00",
    day: 5,
    description: "Músicas para quem está acordado de madrugada.",
    image: "/images/Programas/madrugadaBraba.png",
  },
  // Sábado (day: 6)
  {
    id: 54,
    title: "Fique Ligado nos Eventos",
    host: "",
    time: "",
    day: 6,
    description: "",
    image: "/images/Programas/fimdeSemana.png",
  },
  // Domingo (day: 0)

];

export const prizesData: Prize[] = [
  {
    id: 1,
    title: "Ingressos para Show Premium",
    description: "Ganhe um par de ingressos para o show especial que acontecerá no próximo mês.",
    image: "https://images.pexels.com/photos/3328892/pexels-photo-3328892.jpeg",
    endDate: new Date(2025, 6, 15) // July 15, 2025
  },
  {
    id: 2,
    title: "Kit Exclusivo",
    description: "Concorra a um kit exclusivo com camiseta, boné e caneca personalizada da Rádio Brasil FM.",
    image: "https://images.pexels.com/photos/4066841/pexels-photo-4066841.jpeg",
    endDate: new Date(2025, 5, 30) // June 30, 2025
  },
  {
    id: 3,
    title: "Sessão de Estúdio",
    description: "Grave uma música profissionalmente em nosso estúdio com equipe técnica completa.",
    image: "https://images.pexels.com/photos/164938/pexels-photo-164938.jpeg",
    endDate: new Date(2025, 7, 5) // August 5, 2025
  }
];